

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricardo
 */
public class ConsultarProductoCompraVenta extends javax.swing.JFrame {
public static String valor;    
DefaultTableModel model;  
    /**
     * Creates new form GestionarClientes
     */
    public ConsultarProductoCompraVenta() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setResizable(false);
        setVisible(true);
        setLocation(0,0);
        setTitle("Consultar Producto");      
        setBuscar("");
         
    }
    public void setBuscar (String valor){
       String [] encabezados = {"Id","Descripción","Clave","Código"};
       String [] registros = new String[4];
       //String sql = "SELECT * FROM docente where nom_doc LIKE'%"+valor+"%'";//filtra por nombre
       //String sql = "SELECT * FROM clientes where CONCAT(idclientes,'',NombreCliente) LIKE'%"+valor+"%'";
       String sql = "SELECT * FROM productos where CONCAT(idProductos,'',DescripcionProducto,'',ClaveProducto,'',CodigoBarras) LIKE'%"+valor+"%'";
       model = new DefaultTableModel(null,encabezados);
       conectar conectar1 = new conectar();
       Connection Connection1 = conectar1.conexion();
       
        try {
        Statement st = Connection1.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()){
            registros [0]=rs.getString("idProductos");
            registros [1]=rs.getString("DescripcionProducto");
            registros [2]=rs.getString("ClaveProducto");
            registros [3]=rs.getString("CodigoBarras");
            model.addRow(registros);
        }
        jTableVistaProductos.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, ex);
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVistaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1367, 740));
        getContentPane().setLayout(null);

        jTableVistaProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableVistaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableVistaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVistaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVistaProductos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 480, 640, 199);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 240, 90, 30);

        jTextFieldBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldBuscar);
        jTextFieldBuscar.setBounds(640, 240, 390, 30);

        jPanel2.setBackground(new java.awt.Color(168, 37, 104));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 170, 690);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Proveedores 2.jpeg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, -50, 1280, 790);

        jMenu1.setText("Salir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenuRegresar.setText("Regresar");
        jMenuRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuRegresarMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuRegresar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        // TODO add your handling code here:
         int x = JOptionPane.showConfirmDialog(null, "¿Desea salir del programa?");
                    if (x == JOptionPane.YES_OPTION){
                        System.exit(0);
                    }
//                    else if(x == JOptionPane.NO_OPTION){
//                    }
    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenuRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRegresarMousePressed

        // TODO add your handling code here:
//        GestionarProducto gp1 = new GestionarProducto();
//        gp1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuRegresarMousePressed

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
        // TODO add your handling code here:
        setBuscar(jTextFieldBuscar.getText());
      //  setBuscar(jTextFieldBuscar.getText());
    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    private void jTableVistaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVistaProductosMouseClicked
        if (FacturarCompra.banderaCompra == 1){ 
            DefaultTableModel model = (DefaultTableModel) jTableVistaProductos.getModel();
            valor = model.getValueAt(jTableVistaProductos.getSelectedRow(), 3).toString();
            FacturarCompra.jTextFieldCodigoBarras.setText(valor);
            FacturarCompra.jTextFieldCodigoBarras.requestFocus();
        }else if(FacturarVenta.banderaVenta == 1){
            DefaultTableModel model = (DefaultTableModel) jTableVistaProductos.getModel();
            valor = model.getValueAt(jTableVistaProductos.getSelectedRow(), 3).toString();
            FacturarVenta.jTextFieldCodigoBarras.setText(valor);
            FacturarVenta.jTextFieldCodigoBarras.requestFocus();
        }
        FacturarCompra.banderaCompra = 0;
        FacturarVenta.banderaVenta = 0;
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableVistaProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarProductoCompraVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuRegresar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVistaProductos;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
