
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricardo
 */
public class NuevoProductoComprar extends javax.swing.JFrame {
    public static String valorCodigoBarrar;
    /**
     * Creates new form GestionarProductos
     */
    public NuevoProductoComprar() {
        initComponents();
        setResizable(false);
        setLocation(0,0);
        setTitle("Nuevo Producto"); 
        getContentPane().setBackground(Color.white);
        setCargarNumeroProducto();
        jTextFieldDescripcion.requestFocus();
        valorCodigoBarrar = FacturarCompra.jTextFieldCodigoBarras.getText();
        jTextFieldCodigoBarras.setText(valorCodigoBarrar);
    }
     public void setCargarNumeroProducto(){
        int maxNumProducto=0;
        conectar cn = new conectar();
        Connection con = cn.conexion();
        String sql = "SELECT MAX(idProductos) FROM productos";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                if(rs.getString(1)!= null)
                 maxNumProducto = Integer.valueOf(rs.getString(1).toString());
                else
                 maxNumProducto = 0;
            }
            maxNumProducto = maxNumProducto+1;
            jTextFieldIdProducto.setText(String.valueOf(maxNumProducto));
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, ex);
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldClave = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIdProducto = new javax.swing.JTextField();
        jTextFieldCodigoBarras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSalir = new javax.swing.JMenu();
        jMenuRegresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1367, 740));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Descripción");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 410, 70, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ref");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 440, 20, 17);
        getContentPane().add(jTextFieldDescripcion);
        jTextFieldDescripcion.setBounds(350, 400, 240, 30);
        getContentPane().add(jTextFieldClave);
        jTextFieldClave.setBounds(350, 430, 240, 30);

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jButtonGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGuardarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonGuardar);
        jButtonGuardar.setBounds(350, 470, 240, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 340, 70, 20);

        jTextFieldIdProducto.setEditable(false);
        getContentPane().add(jTextFieldIdProducto);
        jTextFieldIdProducto.setBounds(350, 340, 240, 30);

        jTextFieldCodigoBarras.setEditable(false);
        getContentPane().add(jTextFieldCodigoBarras);
        jTextFieldCodigoBarras.setBounds(350, 370, 240, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Código de Barras");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 380, 104, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lateral 2.jpeg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 230, 420, 400);

        jPanel4.setBackground(new java.awt.Color(168, 37, 104));
        jPanel4.setLayout(null);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 170, 690);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lateral 1.jpeg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 650, 700);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Proveedores 2.jpeg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 0, 1280, 790);

        jMenuSalir.setText("Salir");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        jMenuRegresar.setText("Regresar");
        jMenuRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuRegresarMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuRegresar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        try {
            // TODO add your handling code here:
            Productos Productos1 = new Productos();
            Productos1 .setIdProducto(Integer.parseInt(jTextFieldIdProducto.getText()));
            Productos1.setDetalle(jTextFieldDescripcion.getText());
            Productos1.setClave(jTextFieldClave.getText());
            Productos1.setCodigoBarras(jTextFieldCodigoBarras.getText());
            Productos1.setInsertarProducto(Productos1.getIdProducto(), Productos1.getDetalle(),
            Productos1.getClave(), Productos1.getCodigoBarras());
            FacturarCompra.jTextFieldCodigoBarras.setText(jTextFieldCodigoBarras.getText());
            FacturarCompra.jTextFieldCodigoBarras.requestFocus();
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(GestionarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jMenuSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMousePressed
        // TODO add your handling code here:
         int x = JOptionPane.showConfirmDialog(null, "¿Desea salir del programa?");
                    if (x == JOptionPane.YES_OPTION){
                        System.exit(0);
                    }
//                    else if(x == JOptionPane.NO_OPTION){
//                    }
    }//GEN-LAST:event_jMenuSalirMousePressed

    private void jMenuRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRegresarMousePressed
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_jMenuRegresarMousePressed

    private void jButtonGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGuardarKeyPressed
         try {
            // TODO add your handling code here:
            Productos Productos1 = new Productos();
            Productos1 .setIdProducto(Integer.parseInt(jTextFieldIdProducto.getText()));
            Productos1.setDetalle(jTextFieldDescripcion.getText());
            Productos1.setClave(jTextFieldClave.getText());
            Productos1.setCodigoBarras(jTextFieldCodigoBarras.getText());
            Productos1.setInsertarProducto(Productos1.getIdProducto(), Productos1.getDetalle(),
                    Productos1.getClave(), Productos1.getCodigoBarras());
        } catch (SQLException ex) {
            Logger.getLogger(GestionarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProductoComprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuRegresar;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldClave;
    public static javax.swing.JTextField jTextFieldCodigoBarras;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldIdProducto;
    // End of variables declaration//GEN-END:variables
}
